### ISSUE TITLE
Form hoeft niet in een section

### ISSUE THREAD

**Issue by joostf** [rianneeh/blok-web#4]
https://github.com/rianneeh/blok-web/blob/master/index.html#L55
h1 in de header zetten?

**Comment by rianneeh** [comment]
Besloten zo te laten omdat bij een groter scherm de h1 naast het form komt te staan. Div was geen optie omdat je daar geen h1 in mag zetten. Het form is wel onderdeel van de main content van de pagina, dus kan dat ook niet in de header.
